# Generated by Django 2.2.5 on 2019-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriventapp', '0002_auto_20191003_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
