# Generated by Django 2.2.5 on 2019-11-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriventapp', '0003_userprofile_verified_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_sales_end_date',
            field=models.DateField(null=True),
        ),
    ]
