# Generated by Django 2.2.5 on 2019-11-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriventapp', '0004_auto_20191101_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_sales_end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
