# Generated by Django 2.2.5 on 2019-11-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriventapp', '0005_auto_20191101_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_sales_end_date',
            field=models.DateField(null=True),
        ),
    ]
