# Generated by Django 2.2.5 on 2019-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriventapp', '0006_event_ticket_sales_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
