# Generated by Django 2.2.5 on 2019-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191001_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_barcode',
            field=models.FileField(null=True, upload_to='barcode'),
        ),
    ]
